apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 80           # The port that the service will expose
      targetPort: 80       # Must match the containerPort (80) in your deployment
      nodePort: 32000      # NodePort for external access (within 30000-32767 range)

